name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: GodotWildJam29

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Windows Build
        run: |
          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          mkdir -v -p build/windows
          ls $EXPORT_NAME
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_KEY }}
          CHANNEL: windows
          ITCH_GAME: godot-wild-jam-29
          ITCH_USER: willowblade
          PACKAGE: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Linux Build
        run: |
          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_KEY }}
          CHANNEL: linux
          ITCH_GAME: godot-wild-jam-29
          ITCH_USER: willowblade
          PACKAGE: build/linux

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Web Build
        run: |
          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          mkdir -v -p build/web
          cd $EXPORT_NAME
          godot -v --export "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_KEY }}
          CHANNEL: web
          ITCH_GAME: godot-wild-jam-29
          ITCH_USER: willowblade
          PACKAGE: build/web
